### ISSUE TITLE
Error connecting to MongoDB

### ISSUE THREAD

**Issue by ByBordex** [Arquisoft/InciDashboard_i3a#25]
The conectaron to mongoDB is not working properly.
An exception is thrown whenever the application is run, this error makes impossible to test controllers, services, etc.

![captura de pantalla 2018-03-26 a las 10 49 56](https://user-images.githubusercontent.com/15276132/37896150-749c3de0-30e3-11e8-9912-2ca310a1fe54.png)

**Comment by thewilly** [comment]
I think @eleallegue is aware of that. She told me today something related to it.

**Comment by ByBordex** [comment]
Yes, i esa the One Who told her.

**Comment by thewilly** [comment]
Okay, that's not english hahahahaha xD

**Comment by thewilly** [comment]
@ByBordex can you paste here the full stack-trace?

**Comment by ByBordex** [comment]
Uniovi firewall was blocking conectaron.
