### ISSUE TITLE
README.md implementation

### ISSUE THREAD

**Issue by eleallegue** [Arquisoft/InciDashboard_i3a#28]
Fill in all the information about whow to execute the application

**Comment by eleallegue** [comment]
Still missing information about the program we are going to use to mix all the modules (Docker or something similar possibly) @thewilly @alvarezGarciaMarcos @ByBordex @cristinavn @UO251547

**Comment by thewilly** [comment]
Right now there is no need to "mix" the modules as they work as micro-services. An example of this is the [**module 2**](http://github.com/Arquisoft/Agents_i3a) and the [**module 3**](http://github.com/Arquisoft/InciManager_i3a). Both modules are continuously deployed on to a Heroku container and by means of a [micro-service orchestration system](http://eureka-i3a.herokuapp.com) they communicate between them.

**Example**
 [**Module 2**](http://github.com/Arquisoft/Agents_i3a) is always deployed at **http://i3a-2.herokuapp.com**
 [**Module 3**](http://github.com/Arquisoft/Agents_i3a) is always deployed at **http://i3a-3.herokuapp.com**

When they deploy they register themselves on to **http://eureka-i3a.herokuapp.com**. And when thy need to share data they ask to eureka the address of the resource they need.
