### ISSUE TITLE
Error connecting Codecoverage

### ISSUE THREAD

**Issue by eleallegue** [Arquisoft/InciDashboard_i3a#29]
There's some issue connecting and activating codecoverage in the project.
The .travis.yml seems to be fine, and according to the information provided in the official support page, everything is alright.
https://github.com/codecov/example-java-maven Even in this project, the information about the after-success is right.

**Comment by thewilly** [comment]
Okay, will try to configure it tomorrow morning.

**Comment by thewilly** [comment]
**Possible solution**

Here:
https://github.com/Arquisoft/InciDashboard_i3a/blob/d32673902a43708adb0be69a9f5603c6fd83752e/pom.xml#L101-L106
Add the following plugin:
https://github.com/Arquisoft/InciManager_i3a/blob/6bf439504ecc9bee73a7967364ada267d7277bf3/pom.xml#L102-L120

And then ad the bottom of the file add the following lines:
https://github.com/Arquisoft/InciManager_i3a/blob/6bf439504ecc9bee73a7967364ada267d7277bf3/pom.xml#L140-L191

**Comment by UO251547** [comment]
I tried your solution, adding what you indicated us and it does  not seem to work neither

**Comment by thewilly** [comment]
Hi @UO251547 can you specify on which branch did you implemented? just to take a look and see if codecov had process your brach.

**Comment by UO251547** [comment]
I did it on master, i just checked again and it looks like codecov has been activated

**Comment by thewilly** [comment]
Awesome!
