### ISSUE TITLE
*Check optionals and delete the ones we did not implement

### ISSUE THREAD

**Issue by UO251547** [Arquisoft/InciDashboard_i3a#44]
We need to check the optionals from the documentation and delete the ones we did not implement, as we will be asked for them in the final presentation otherwise.

**Comment by ByBordex** [comment]
This issue should be placed in [Inci_i3a](https://github.com/Arquisoft/Inci_i3a) repository since every module has to change its documentation.

**Comment by ghost** [comment]
We have discussed them and deleted the ones that have not been implemented
