### ISSUE TITLE
Fix typo for the submit button at the edit template for incidents.

### ISSUE THREAD

**Issue by thewilly** [Arquisoft/InciDashboard_i3a#49]
https://github.com/Arquisoft/InciDashboard_i3a/blob/113a37ba1562330dab7f47d83a2e0f9e986ea661/src/main/resources/templates/incident/edit.html#L15

Where you see `incident.id` change to `incident.incidentId` and should work perfectly.

**Comment by eleallegue** [comment]
DONE! 🥇
