### ISSUE TITLE
Problems with the edition of the incident

### ISSUE THREAD

**Issue by eleallegue** [Arquisoft/InciDashboard_i3a#51]
There are some problems with the edition of the incident.
The whole page crashes if something fails

**Comment by eleallegue** [comment]
**UPDATE**
The edition view now is shown, and by the log history, the edition is correctly done, but there is something wrong with the database or something, because when you are redirected to the open incident's list, the incident is still there, and there's no lead to the incident you have just edited to IN_PROCESS
@thewilly I wish you can help me out

**Comment by thewilly** [comment]
Consider it done
